name: Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          API_ID: ${{secrets.API_ID}}
          API_HASH: ${{secrets.API_HASH}}
          SESSION: ${{secrets.SESSION}}
          REDIS_URI: ${{secrets.REDIS_URI}}
          REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          LOG_CHANNEL: ${{secrets.LOG_CHANNEL}}
          BOT_TOKEN: ${{secrets.BOT_TOKEN}}
